### ISSUE TITLE
Not working with ipython

### ISSUE THREAD

**Issue by pablogsal** [danrobinson/tracestack#3]
The following piece of code

``` python
import tracestack
tracestack.on()
1 / 0
```

**does** work on the standard python interpreter (2.7.10) but no in ipython (4.0.0). The exit in ipython is obviously:

``` python
In [1]: import tracestack

In [2]: tracestack.on()

In [3]: 1 / 0
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-3-b710d87c980c> in <module>()
----> 1 1 / 0

ZeroDivisionError: integer division or modulo by zero
```

and nothing happens.

Some ideas?

**Comment by danrobinson** [comment]
Thanks.  It looks like IPython doesn't use `sys.excepthook`.

I think we'll have to test for IPython and, if the user is using it, override the `showsyntaxerror` and `showtraceback` methods of `IPython.core.interactiveshell.InteractiveShell` to have them invoke the custom handler.

Conveniently, this is precisely what we do for python's interactive interpreter in `console.py`; inconveniently `code.InteractiveInterpreter` is an old-style class in Python 2.7 so multiple inheritance may not be possible.  I'll take a look and try to patch tonight or tomorrow.
